#ScopusDivisions
divisions = {
 'BioChem': {'name': 'biological chemistry',
  'keywords': ['biological chemistry',
   'cytochrome*',
   'biomolecule*',
   'bioorthogonal chem*',
   'enzyme chem*',
   'RNA based therap*',
   'bioconjugate',
   'drug discovery',
   'structural biology',
   'chemical signaling',
   'protein folding',
   'protein aggregation',
   'organofluorine',
   'genome engineering',
   'biosynthesis',
   'chem* biology']},
 'ChemInfo': {'name': 'chemical information',
  'keywords': ['chemical informatics',
   'bio* modeling',
   'computational chemistry',
   'cheminformatic*',
   'chemical info*',
   'drug discovery',
   'chem* database*',
   'chem* librar*',
   'chem* vocabulary',
   'materials informatic*'
   'nanomedicine*']},
 'ChemTox': {'name': 'chemical toxicology',
  'keywords': ['toxi*', 'antibody drug conjugate*', 'chemical exposure*']},
 'ComChem': {'name': 'computers in chemistry',
  'keywords': ['chem* comput*',
   'drug design',
   'drug discovery',
   'computational chem*',
   'molecular mechanics',
   'multiscale modeling',
   'computational quantum chem*',
   'quantum comp*',
   'quantum dynamic*',
   'multiscale computational modeling',
   'computational model* of chem*',
   'chem* database*',
   'material* database*',
   'protein database*',
   'rna design*',
   'density functional theory',
   'computational cataly*',
   'molecular model*',
   'chem* librar*',
   'chem* screen*',
   'molecular recognition',
   'computer-aided peptide design']},
 'MediChem': {'name': 'medicinal chemistry',
  'keywords': ['medic* chem*',
   'drug discovery',
   'immunomodulator*',
   'lipophil*',
   'protein degradation',
   'sulfonamide*',
   'glioblastoma*',
   'pancreatic cancer',
   'drug design',
   'protein interaction*',
   'neurodegeneration',
   'targeting rna',
   'brain penetration',
   'neuro-oncology',
   'virtual screening'
   'opioid epidemic',
   'gasotransmitter*',
   'pi3k inhibitor*',
   'atropisomer*',
   'cyp450 enzyme*',
   'muscarinic receptor*',
   'hiv 1 infection',
   'neuropathic pain',
   'antibiotic*',
   'kinase inhibitor*',
   'macrocycle*',
   'cyclopeptide*',
   'misfolded protein*',
   'biomolecular structure*',
   'biomolecular dynamic*',
   'biophysic*',
   'ion*',
   '2d material*',
   'two dimensional material*',
   'amyloid','interleukin']},
 'OrgChem': {'name': 'organic chemistry',
  'keywords': ['organic chem*',
   'asymmetric synthes*',
   'biocataly*','molecular recognition','molecular self assembly','peptide*',
   'protein-ligand interaction*',
   'protein-peptide interaction*',
   'protein-peptide binding*',
   'amino acid*',
   'enzyme engineering',
   'chemical biology']}}